# Generated by Django 4.1.7 on 2023-04-09 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunler', '0009_sepet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam', models.IntegerField()),
                ('odendiMi', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sepet', models.ManyToManyField(to='urunler.sepet')),
            ],
        ),
    ]
